<?php
/**
 * Copyright © Auer All rights reserved.
 * See COPYING.txt for license details.
 */

use Superb\QA\Block\Adminhtml\Commands;
use Superb\QA\Controller\Adminhtml\Commands\Run;
use Superb\QA\Controller\Adminhtml\Commands\Log;

/** @var Commands $block */

?>
<div class="page-main-actions">
    <form method="post"
          data-mage-init='{"QACommand":{"runUrl":"<?= $block->getUrl(Run::URL); ?>", "logUrl":"<?= $block->getUrl(Log::URL); ?>"}}'>
        <div class="admin__field">
            <div class="admin__field-label">
                <label for="command">Command:</label>
            </div>
            <div class="admin__field-control">
                <select name="command" id="command" class="admin__control-select">
                    <?php if ($block->isAllowedCustomCommand()): ?>
                        <option value="" selected>Manual command</option>
                    <?php endif; ?>
                    <optgroup label="Previous used">
                        <?php foreach ($block->getPrevious() as $id => $command): ?>
                            <option
                                value="<?= $block->escapeHtmlAttr($command); ?>"
                                data-id="<?= $block->escapeHtmlAttr($id); ?>"><?= $block->escapeHtml($command); ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                    <optgroup label="Commands">
                        <?php foreach ($block->getCommands() as $command => $description): ?>
                            <option
                                value="<?= $block->escapeHtmlAttr($command); ?>"><?= $block->escapeHtml($description); ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                    <?php if (count($block->getCustoms())): ?>
                        <optgroup label="Customs">
                            <?php foreach ($block->getCustoms() as $command => $description): ?>
                                <option
                                    value="<?= $block->escapeHtmlAttr($command); ?>"><?= $block->escapeHtml($description); ?></option>
                            <?php endforeach; ?>
                        </optgroup>
                    <?php endif; ?>
                </select>
                <input type="hidden" name="command_id">
            </div>
        </div>
        <div class="admin__field">
            <div class="admin__field-label">
                <label for="args">Arguments:</label>
            </div>
            <div class="admin__field-control">
                <input type="text" name="args" id="args" class="admin__control-text">
            </div>
        </div>
        <div class="admin__action">
            <div class="admin__field-messages">
                <div id="messages">
                    <div class="messages">
                    </div>
                </div>
            </div>
            <div class="admin__field-control">
                <button id="run" title="<?= $block->escapeHtmlAttr(__('Run Command')) ?>" type="submit"
                        class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                    <span><?= $block->escapeHtml(__('Run')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="response-block">
    <pre class="line-numbers"><code class="language-bash"></code></pre>
</div>
