<?php
/**
 * Copyright © Auer All rights reserved.
 * See COPYING.txt for license details.
 */

use Superb\QA\Block\Adminhtml\Cron;
use Superb\QA\Controller\Adminhtml\Cron\Run;
use Superb\QA\Controller\Adminhtml\Commands\Log;

/** @var Cron $block */

?>
<div class="page-main-actions">
    <form method="post" data-mage-init='{"QACommand":{"runUrl":"<?= $block->getUrl(Run::URL); ?>", "logUrl":"<?= $block->getUrl(Log::URL); ?>"}}'>
        <div class="admin__field">
            <div class="admin__field-label">
                <label for="cron">Cron:</label>
            </div>
            <div class="admin__field-control">
                <select name="cron" id="cron" class="admin__control-select">
                    <optgroup label="Previous used">
                        <?php foreach ($block->getPrevious() as $id => $command): ?>
                            <option
                                value="<?= $block->escapeHtmlAttr($command); ?>"
                                data-id="<?= $block->escapeHtmlAttr($id); ?>"><?= $block->escapeHtml($command); ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                    <optgroup label="Cron Jobs">
                        <?php foreach ($block->getCronJobs() as $name => $description): ?>
                            <option
                                value="<?= $block->escapeHtmlAttr($name); ?>"><?= $block->escapeHtml($description); ?></option>
                        <?php endforeach; ?>
                    </optgroup>
                </select>
                <input type="hidden" name="command_id">
            </div>
        </div>
        <div class="admin__action">
            <div class="admin__field-messages">
                <div id="messages">
                    <div class="messages">
                    </div>
                </div>
            </div>
            <div class="admin__field-control">
                <button id="run" title="<?= $block->escapeHtmlAttr(__('Run Cron')) ?>" type="submit"
                        class="action-default scalable save primary ui-button ui-corner-all ui-widget">
                    <span><?= $block->escapeHtml(__('Run')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
<div class="response-block">
    <pre class="line-numbers"><code class="language-bash"></code></pre>
</div>
