<?php
/**
 * Copyright © Auer All rights reserved.
 * See COPYING.txt for license details.
 */

use Superb\QA\Block\Adminhtml\LogsView;

/** @var LogsView $block */

?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?php foreach ($block->getActions() as $key => $action):
                    $hookId = 'buttonId' . uniqid();
                    ?>
                    <button id="<?= $block->escapeHtmlAttr($key) ?>"
                            backend-button-widget-hook-id="<?= $hookId ?>"
                            title="<?= $block->escapeHtmlAttr($action['label']) ?>"
                            type="button"
                            class="action-default scalable <?= $block->escapeHtmlAttr($key) ?>"
                            onclick="setLocation('<?= $action['href']; ?>')"
                    >
                        <span><?= $block->escapeHtml($action['label']) ?></span>
                    </button>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<?php
$content = $block->getContent();
?>
<div class="log-viewer-container">
    <pre class="line-numbers"><code class="language-log"
                                    data-length="<?= $block->escapeHtmlAttr(strlen($content)) ?>"><?= $block->escapeHtml($content) ?></code></pre>
</div>
<script type="text/javascript">
    require([
        "jquery"
    ], function ($) {
        function debounce(callback, delay) {
            let timer;
            return function () {
                clearTimeout(timer);
                timer = setTimeout(() => {
                    callback();
                }, delay)
            }
        }

        function resizeLogViewer() {
            let logViewer = $('.log-viewer-container pre');
            const windowHeight = window.innerHeight;
            const top = logViewer[0].getBoundingClientRect().top;
            const bottomPadding = 40;
            const newHeight = windowHeight - top - bottomPadding;
            logViewer.css('max-height', newHeight + 'px');
        }

        debounce(resizeLogViewer, 100);
        window.addEventListener('resize', debounce(resizeLogViewer, 100));
        setTimeout(debounce(resizeLogViewer, 100), 300);
    });
</script>

