<?php
/**
 * Copyright © Auer All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Superb\QA\Block\Adminhtml\LogsView;

/**
 * @var LogsView           $block
 * @var Escaper            $escaper
 * @var SecureHtmlRenderer $secureRenderer
 */

?>
<div class="page-main-actions">
    <div class="page-actions-placeholder"></div>
    <div class="page-actions" data-ui-id="page-actions-toolbar-content-header">
        <div class="page-actions-inner">
            <div class="page-actions-buttons">
                <?php foreach ($block->getActions() as $key => $action): ?>
                    <button id="<?= $escaper->escapeHtmlAttr($key) ?>"
                            title="<?= $escaper->escapeHtmlAttr($action['label']) ?>"
                            type="button"
                            class="action-default scalable <?= $escaper->escapeHtmlAttr($key) ?>"
                            onclick="setLocation('<?= $action['href'] ?>')"
                    >
                        <span><?= $escaper->escapeHtml($action['label']) ?></span>
                    </button>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>
<?php
$content = $block->getContent();
?>
<div class="log-viewer-container">
    <pre class="line-numbers"><code class="language-log"
                                    data-length="<?= $escaper->escapeHtmlAttr(strlen($content)) ?>"><?= $escaper->escapeHtml($content) ?></code></pre>
</div>

<?php
$content = <<<JS
    require([
        "jquery"
    ], function ($) {
        function debounce(callback, delay) {
            let timer;
            return function () {
                clearTimeout(timer);
                timer = setTimeout(() => {
                    callback();
                }, delay)
            }
        }

        function resizeLogViewer() {
            let logViewer = $('.log-viewer-container pre');
            const windowHeight = window.innerHeight;
            const top = logViewer[0].getBoundingClientRect().top;
            const bottomPadding = 40;
            const newHeight = windowHeight - top - bottomPadding;
            logViewer.css('max-height', newHeight + 'px');
        }

        debounce(resizeLogViewer, 100);
        window.addEventListener('resize', debounce(resizeLogViewer, 100));
        setTimeout(debounce(resizeLogViewer, 100), 300);
    });
JS;

echo $secureRenderer->renderTag('script', [], $content);
